// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgnhnunpuhdozxquoion.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnbmhudW5wdWhkb3p4cXVvaW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODU5NDcsImV4cCI6MjA2OTM2MTk0N30.5qV3lqG7CcBDt0Z7sqE2hGsVObK6-ErL57zyMKR2X_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});